### PR TITLE
Initial support for MCDM driver

### PR DESCRIPTION
**Pull request by mariodruiz**
### Describe the problem solved by the commit

Add support for MCDM driver

### How is the problem solved?

Rework npu top to show dummy app names

### Are there any risks associated to the change?

More stress test with the new driver should be done

### Is there a documentation impact?

No

### Checklist

- [x] Existing and new test pass
- [x] I read and I accept the [CONTRIBUTING.md](https://github.com/AMDResearch/Riallto/blob/main/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Review by skalade — CHANGES_REQUESTED** [review]
Hey Mario, the changes to the tests dir don't seem to be relevant to this PR. Could u remove them and maybe open a new one for the tests improvements? Makes easier to track down changes it history

**Comment by mariodruiz** [comment]
@skalade the `tests/test_endtoend.py` fails with the new driver. I assumed due to the kernel accessing more data that is supposed to.

Do you want me to move `tests/test_endtoend.py` to a different PR? 
I agree with the comments for other tests

**Comment by mariodruiz** [comment]
@STFleming 

> Do you know if this is something that is reported/accessible via XRT? It might be possible to reconstruct the name of the running apps using this?

I am not sure. xrt-smi is the same tool in Linux, so this PR technically works in Linux, albeit the apps show up as `app<id>`

**Comment by skalade** [comment]
> @skalade the `tests/test_endtoend.py` fails with the new driver. I assumed due to the kernel accessing more data that is supposed to.
> 
> Do you want me to move `tests/test_endtoend.py` to a different PR? I agree with the comments for other tests

Ah ok sorry I didn't realize it was tied to the changes

**Review by STFleming — APPROVED** [review]

**Pull request merged**
